### Create AWS Node

POST http://127.0.0.1:5000/api/nodes
Content-Type: application/json

{
    "name": "AWS Primary",
    "provider": "AWS",
    "region": "us-east-1"
}


### Get All Nodes

GET http://127.0.0.1:5000/api/nodes

### Create metrics for a specific node

POST http://127.0.0.1:5000/api/metrics
Content-Type: application/json

{
    "node_id": 1,
    "cpu_usage": 65.0,
    "memory_usage": 70.0,
    "disk_usage": 45.0,
    "response_time": 120.0
}

### Get all metrics

GET http://127.0.0.1:5000/api/metrics


### Get all cloud nodes

GET http://127.0.0.1:5000/api/nodes



### Add Health Metric

POST http://127.0.0.1:5000/api/metrics
Content-Type: application/json

{
    "node_id": 1,
    "cpu_usage": 40,
    "memory_usage": 50,
    "disk_usage": 40,
    "response_time": 100
}



### Check Node 1 Health

GET http://127.0.0.1:5000/api/nodes/1/health


### Add WARNING metric

POST http://127.0.0.1:5000/api/metrics
Content-Type: application/json

{
    "node_id": 1,
    "cpu_usage": 80,
    "memory_usage": 60,
    "disk_usage": 50,
    "response_time": 200
}

### Add FAILED metric

POST http://127.0.0.1:5000/api/metrics
Content-Type: application/json

{
    "node_id": 1,
    "cpu_usage": 95,
    "memory_usage": 92,
    "disk_usage": 50,
    "response_time": 2500
}

### Check Node 1 Health

GET http://127.0.0.1:5000/api/nodes/1/health



### Create FAILED metric

POST http://127.0.0.1:5000/api/metrics
Content-Type: application/json

{
    "node_id": 1,
    "cpu_usage": 95,
    "memory_usage": 92,
    "disk_usage": 50,
    "response_time": 2500
}

### Get failure events

GET http://127.0.0.1:5000/api/failover/events