### Create AWS Node

POST http://127.0.0.1:5000/api/nodes
Content-Type: application/json

{
    "name": "AWS Primary",
    "provider": "AWS",
    "region": "us-east-1"
}


### Get All Nodes

GET http://127.0.0.1:5000/api/nodes

### Create metrics for a specific node

POST http://127.0.0.1:5000/api/metrics
Content-Type: application/json

{
    "node_id": 1,
    "cpu_usage": 65.0,
    "memory_usage": 70.0,
    "disk_usage": 45.0,
    "response_time": 120.0
}

### Get all metrics

GET http://127.0.0.1:5000/api/metrics