"""Add cloud node instance ID

Revision ID: 0447c832064a
Revises: c32aa1578e98
Create Date: 2026-09-22 21:30:28.695023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0447c832064a'
down_revision = 'c32aa1578e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud_nodes', schema=None) as batch_op:
        batch_op.drop_column('instance_id')

    # ### end Alembic commands ###
