"""create cloud nodes table

Revision ID: 254fdc3d08dd
Revises: 
Create Date: 2026-08-08 00:53:50.914238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254fdc3d08dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cloud_nodes')
    # ### end Alembic commands ###
